#+TITLE: My C++ notes

This document captures basic concepts and features used in modern C++. I tend to learn
better by example, so I will briefly describe and concept/feature and then give example(s)
to show how it is used.

*Note:* This document is in progress.

* Setup
These notes will be in [[https://en.wikipedia.org/wiki/Literate_programming][literate programming]] style. All code will be compiled and executed using
the [[https://clang.llvm.org/][clang]] compiler. Specifically, [[https://github.com/spraza/dotfiles/blob/master/.emacs#L59][this command]] was used. In some examples, I also plan to do
benchmarking using [[https://github.com/facebook/folly/blob/master/folly/docs/Benchmark.md][this library]]. 

* Resources
- Scott Meyer's excellent books on C++ practices: https://www.aristeia.com/books.html
- Andrei Alexandrescu's Modern C++ design: https://erdani.com/index.php/books/modern-c-design/
- Bo's C++ videos [[https://www.youtube.com/user/BoQianTheProgrammer/playlists][on youtube]].
- Stackoverflow and Quora communities

* Types

** Basic 

#+BEGIN_SRC C++ :exports both
  // Toy example -- not production code!
  #include <iostream>

  using namespace std;

  int main() {
    cout << "hey\n";
  }
#+End_SRC

#+RESULTS:
: hey

** Container / STL

** Auto

* Smart pointers

Ownership and move semantics.

* Lambdas

* Concurrency

* Move semantics

* Templates 

Also cover static vs dynamic typing and tradeoffs.

* Metaprogramming
